name: com_cingulo_sample
description: A flutter implementation with network call, error handling, streams, and BloC..

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  analyzer: ^0.34.0
  flutter:
    sdk: flutter
  pedantic: ^1.7.0

  # Dependency Injection
  build_runner: ^1.0.0
  inject:
    path: ./vendor/inject.dart/package/inject

  #Internationalization
  flutter_localizations:
    sdk: flutter

  # Analytics
  package_info: ^0.4.0+6

  # Navigation
  fluro: ^1.4.0

  # Rx
  rxdart: ^0.22.0

  # Network call
  dio: ^2.1.7

  # Local storage
  shared_preferences: ^0.5.3

  # Access an external url by browser
  url_launcher: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  inject_generator:
    path: ./vendor/inject.dart/package/inject_generator

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
